SET(MISTRAL_SEARCH_PATHS
	~/projects/mistral)

FIND_PATH(MISTRAL_INCLUDE_DIR mistral.h
	PATHS ${MISTRAL_SEARCH_PATHS}
	PATH_SUFFIXES include
	NO_DEFAULT_PATH)

FIND_LIBRARY(MISTRAL_LIBRARY mistral
	PATHS ${MISTRAL_SEARCH_PATHS}
	PATH_SUFFIXES lib build
	NO_DEFAULT_PATH)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(Mistral DEFAULT_MSG MISTRAL_LIBRARY MISTRAL_INCLUDE_DIR)

IF (MISTRAL_FOUND)
	GET_FILENAME_COMPONENT(MISTRAL_LIBRARY_DIR ${MISTRAL_LIBRARY} DIRECTORY)
	SET(MISTRAL_LIBRARIES 
		${MISTRAL_LIBRARY}
		${MISTRAL_LIBRARY_DIR}/parser/libparser.a
		${MISTRAL_LIBRARY_DIR}/smtparser/libsmtparser.a
		gmp)
	SET(MISTRAL_INCLUDE_DIRS 
		${MISTRAL_INCLUDE_DIR} 
		${MISTRAL_INCLUDE_DIR}/cnode
		${MISTRAL_INCLUDE_DIR}/elimination
		${MISTRAL_INCLUDE_DIR}/numeric-lib
		${MISTRAL_INCLUDE_DIR}/parser
		${MISTRAL_INCLUDE_DIR}/sat-solver
		${MISTRAL_INCLUDE_DIR}/smt-solver
		${MISTRAL_INCLUDE_DIR}/solver
		${MISTRAL_INCLUDE_DIR}/term)
ENDIF (MISTRAL_FOUND)